'use client';
import { useEffect, useState, type FormEvent } from 'react';
import type { SiteContent } from '@/lib/cms/types';
import './admin.css';
import Enquiries from './Enquiries';
type Value = string|number|boolean|null|Value[]|{[key:string]:Value};
const templates:Record<string,Value>={
  roles:{id:'new-role',title:'New role',location:'Saudi Arabia',type:'Full time',description:'Describe this opportunity.',applyEmail:'hello@yellostack.com',open:true},
  clients:{id:'new-client',name:'Client name',image:'',url:''},
  posts:{slug:'new-article',title:'New article',date:new Date().toISOString().slice(0,10),category:'News',summary:'Article introduction.',paragraphs:['Write your article here.'],source:'',coverImage:''},
  pages:{slug:'new-page',title:'New page',eyebrow:'Yellostack',intro:'Page introduction.',kind:'company',source:'',sections:[{title:'Section heading',body:'Section content.',image:'',imageAlt:''}]},
};
function label(value:string){return value.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ');}
function Field({value,path,onChange}:{value:Value;path:string;onChange:(value:Value)=>void}) {
  const name=path.split('.').at(-1)!;
  if(typeof value==='boolean')return <label className="cms-check"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label(name)}</label>;
  if(typeof value==='string'||typeof value==='number')return <label className="cms-field"><span>{label(name)}</span>{name==='kind'?<select value={String(value)} onChange={e=>onChange(e.target.value)}>{['company','service','directory','contact','portfolio'].map(v=><option key={v}>{v}</option>)}</select>:typeof value==='number'?<input type="number" value={value} onChange={e=>onChange(Number(e.target.value))}/>:value.length>90||/description|body|intro|summary|paragraph/i.test(path)?<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>;
  if(Array.isArray(value))return <div className="cms-array">{value.map((item,index)=><details key={index} className="cms-item" open={typeof item!=='object'}><summary>{typeof item==='object' && item!==null && !Array.isArray(item)?String(item.title||item.name||item.step||item.label||`Item ${index+1}`):`Item ${index+1}`}</summary><div className="cms-item-body"><Field value={item} path={`${path}.${index}`} onChange={next=>onChange(value.map((old,i)=>i===index?next:old))}/><div className="cms-row"><button type="button" disabled={index===0} onClick={()=>{const next=[...value];[next[index-1],next[index]]=[next[index],next[index-1]];onChange(next);}}>Move up</button><button type="button" onClick={()=>{if(confirm('Remove this item from the draft?'))onChange(value.filter((_,i)=>i!==index));}}>Remove</button></div></div></details>)}<button type="button" onClick={()=>{const sample=templates[path]??value[0]??'';const next=structuredClone(sample);if(next&&typeof next==='object'&&!Array.isArray(next)&&'id' in next)next.id=crypto.randomUUID();onChange([...value,next]);}}>+ Add {label(name)}</button></div>;
  if(value && typeof value==='object')return <div className="cms-fields">{Object.entries(value).map(([key,entry])=><div key={key}>{entry && typeof entry==='object'?<details className="cms-item"><summary>{label(key)}</summary><div className="cms-item-body"><Field value={entry} path={`${path}.${key}`} onChange={next=>onChange({...value,[key]:next})}/></div></details>:<Field value={entry} path={`${path}.${key}`} onChange={next=>onChange({...value,[key]:next})}/>}</div>)}</div>;
  return null;
}
async function api(action:string,body?:unknown){const response=await fetch('/api/cms/'+action,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;}
const tabs: [keyof SiteContent,string][]=[['site','Homepage data'],['copy','Headings & labels'],['media','Images'],['pages','Inner pages'],['posts','Blog articles'],['roles','Open roles'],['clients','Client logos']];
export default function AdminPanel(){
  const [configured,setConfigured]=useState<boolean|null>(null);const [signedIn,setSignedIn]=useState(false);const [content,setContent]=useState<SiteContent|null>(null);const [revision,setRevision]=useState(0);const [tab,setTab]=useState<keyof SiteContent>('site');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [dirty,setDirty]=useState(false);const [search,setSearch]=useState('');const [upload,setUpload]=useState('');
  async function load(){const data=await api('content');setContent(data.content);setRevision(data.revision);setSignedIn(true);setDirty(false);}
  useEffect(()=>{api('status').then(data=>{setConfigured(data.configured);if(data.configured)api('session').then(()=>load()).catch(()=>{});}).catch(()=>setMessage('Cannot connect to the CMS.'));},[]);
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);try{await api('login',{email:form.get('email'),password:form.get('password')});await load();setMessage('Signed in.');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
  async function save(publish:boolean){if(!content)return;setBusy(true);setMessage('');try{const result=await api(publish?'publish':'save',{content,revision});setRevision(result.revision);setDirty(false);setMessage(publish?'Published. Refresh the website to see your changes.':'Draft saved. Public content has not changed.');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
  function exportDraft(){const url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='yellostack-content-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <div className="cms"><header className="cms-header"><a href="/">Yello<span>Stack</span></a><span>CONTENT STUDIO</span>{signedIn&&<button disabled={busy} onClick={async()=>{if(dirty&&!confirm('Leave without saving your draft?'))return;try{await api('logout',{});setSignedIn(false);setContent(null);setDirty(false);}catch(error){setMessage((error as Error).message);}}}>Sign out</button>}</header>
    <main className="cms-main">{message&&<p role="status" className="cms-message">{message}</p>}
      {configured===null?<p>Checking CMS connection…</p>:!configured?<section className="cms-login"><h1>Connect your content studio.</h1><p>Add SUPABASE_URL and SUPABASE_ANON_KEY in Vercel, run the included database migration and create your editor account. Full instructions are in <code>docs/CMS-DEPLOYMENT.md</code>.</p><p>The public website continues to use its bundled content until you publish.</p></section>:!signedIn?<form onSubmit={login} className="cms-login"><p>YELLOSTACK / ADMIN</p><h1>Welcome back.</h1><label>Email<input name="email" type="email" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button disabled={busy}>{busy?'Signing in…':'Sign in'}</button><p>Editor access only. Sessions expire after one hour; save drafts regularly.</p></form>:content&&<>
      <div className="cms-toolbar"><div><h1>Your website, in your hands.</h1><p>Revision {revision} · {dirty?'Unsaved changes':'Draft up to date'}</p></div><div className="cms-row"><button disabled={busy} onClick={exportDraft}>Export backup</button><label className="cms-import">Import backup<input type="file" accept="application/json,.json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1500000)throw new Error('Backup exceeds 1.5 MB');const imported=JSON.parse(await file.text());if(!imported.site||!Array.isArray(imported.pages)||!Array.isArray(imported.posts)||!imported.copy||!imported.media)throw new Error('Not a Yellostack content backup');if(confirm('Replace the current editor content with this backup? This will not publish it.')){setContent(imported);setDirty(true);setMessage('Backup loaded into the editor. Review it, then save or publish.');}}catch(error){setMessage((error as Error).message);}finally{e.target.value='';}}}/></label><button disabled={busy} onClick={()=>save(false)}>Save draft</button><button disabled={busy} className="cms-publish" onClick={()=>{if(confirm('Publish this draft to the public website?'))save(true);}}>Publish</button><a href="/" target="_blank" rel="noreferrer">View website ↗</a></div></div>
      <Enquiries/><div className="cms-workspace"><nav aria-label="CMS sections">{tabs.map(([key,title])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setSearch('');}}>{title}</button>)}<button onClick={()=>{if(!dirty||confirm('Discard unsaved edits and reload the last saved draft?'))load().catch(error=>setMessage(error.message));}}>Reload saved draft</button></nav><fieldset disabled={busy} className="cms-editor"><h2>{tabs.find(([key])=>key===tab)?.[1]}</h2>
      {['media','clients','pages','posts'].includes(tab)?<div className="cms-upload"><label>Upload image (PNG, JPEG, WebP, AVIF; maximum 3 MB)<input type="file" accept="image/png,image/jpeg,image/webp,image/avif" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const form=new FormData();form.append('file',file);const response=await fetch('/api/cms/upload',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);setUpload(data.url);setMessage('Image uploaded. Copy its URL into an image field, then publish.');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);e.target.value='';}}}/></label>{upload&&<label>Uploaded image URL<input readOnly value={upload} onFocus={e=>e.target.select()}/><button onClick={()=>navigator.clipboard.writeText(upload).then(()=>setMessage('Image URL copied.')).catch(()=>setMessage('Select and copy the URL manually.'))}>Copy URL</button></label>}</div>:null}
      {tab==='copy'||tab==='media'?<><label className="cms-field"><span>Find a field</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by text or field name"/></label>{Object.entries(content[tab]).filter(([key,value])=>(key+' '+value).toLowerCase().includes(search.toLowerCase())).map(([key,value])=><Field key={key} path={key} value={value} onChange={next=>{setContent({...content,[tab]:{...content[tab],[key]:next}});setDirty(true);}}/>)}</>:<Field value={content[tab] as unknown as Value} path={tab} onChange={next=>{setContent({...content,[tab]:next});setDirty(true);}}/>}
      </fieldset></div></>}
    </main></div>;
}
